project:
  type: book

book:
  title       : Reproducible data treatment with R
  subtitle    : An introduction
  # author      : 
  #   - name: "[Colin BOUSIGE](mailto:colin.bousige@cnrs.fr)"
  #     email: colin.bousige@cnrs.fr
  #     affiliation: "[Laboratoire des Multimat√©riaux et Interfaces](http://lmi.cnrs.fr/)<br>Lyon, France"
  date        : now
  url         : 'https\://lmi.cnrs.fr/r/'
  cover-image : logo.png
  google-analytics: google_analytics.html
  repo-url: https://github.com/colinbousige/Rclass
  repo-actions: 
    - source
    - issue
  chapters:
    - index.qmd
    - 01-about.qmd
    - 02-stats.qmd
    - 03-getting_ready.qmd
    - 05-variables.qmd
    - 06-vectors.qmd
    - 07-dataframes.qmd
    - 08-reading_files.qmd
    - 09-lists.qmd
    - 10-functions.qmd
    - 11-conditions_loops.qmd
    - 12-plotting.qmd
    - 13-3d_plots.qmd
    - 14-fitting.qmd
    - 15-rmarkdown.qmd
    - 16-shiny.qmd
    - 17-units.qmd
    - 18-exercises.qmd
  # navbar:
  #   search: true
  #   right:
  #     - icon: github

format:
  html:
    theme     : cosmo
    linkcolor : "#3d54cb"
